site_name: Transiter 1.0.0-dev
docs_dir: src
theme:
  name: material
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
        
  #  scheme: default
  #  primary: blue
  #  accent: blue
  extra_css: extra.css
  extensions: []
plugins:
  - search

repo_url: https://github.com/jamespfennell/transiter
copyright: >
  Transiter is licensed under the
  <a href='https://raw.githubusercontent.com/jamespfennell/transiter/master/LICENSE'>MIT license</a>
  <!-- 6808e24437044a523cf793e1f93f6924-90388b1a0c91760551522c59a4088557-7a55dcd8cb6f2093d5ab9a9b7997d9cc -->
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.details
  - toc:
      baselevel: 1
# Page tree
nav:
  - Home: index.md
  - tour.md
  - systems.md
  - Deployment and monitoring: deployment.md
  - API reference:
      - Introduction: api/index.md
      - Public API (resources): api/public_resources.md
      - Public API (endpoints): api/public_endpoints.md
      - Admin API: api/admin.md
