name: Build

on: [push, pull_request]

jobs:
  build-and-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.18.0'
      
      - name: Go build
        run: go build .
  
      - name: Launch Postgres
        run: docker run -d --env POSTGRES_USER=transiter --env POSTGRES_PASSWORD=transiter --env POSTGRES_DB=transiter -p 5432:5432 postgres:12

      - name: Go test
        run: go test ./...
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build the Docker image
        uses: docker/build-push-action@v4
        with:
          tags: jamespfennell/transiter:latest
          outputs: type=docker
          context: .

      - name: End-to-end tests (setup)
        run: docker-compose -f tests/endtoend/compose.yml up --build --detach sourceserver transiter db

      - name: End-to-end tests (run)
        run: docker-compose -f tests/endtoend/compose.yml up --build --exit-code-from testrunner testrunner

      - name: Linter (staticcheck)
        run: go install honnef.co/go/tools/cmd/staticcheck@2023.1 && staticcheck ./...

      - name: Linter (errcheck)
        # This runs errcheck, counts the number of failures, and asserts that it's equal to two.
        # There are currently two sites where errors are ignored. Because these are in code generated
        # by sqlc, we can't fix them.
        run: go install github.com/kisielk/errcheck@v1.6.3 && errcheck ./... | wc -l | grep "^2$"

      - name: Login to DockerHub
        uses: docker/login-action@v2
        # Only push to Docker Hub if this workflow is a push to mainline
        if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}
        with:
          username: jamespfennell
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v4
        # Only push to Docker Hub if this workflow is a push to mainline
        if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}
        with:
          tags: |
            jamespfennell/transiter:build-${{ github.run_number }}
            jamespfennell/transiter:latest
          context: .
          push: true

  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build the Docker image
        uses: docker/build-push-action@v4
        with:
          file: docs/Dockerfile
          tags: jamespfennell/transiter-docs:latest
          outputs: type=docker
          context: .

      - name: Login to DockerHub
        uses: docker/login-action@v2
        # Only push to Docker Hub if this workflow is a push to mainline
        if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}
        with:
          username: jamespfennell
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push to Docker Hub
        uses: docker/build-push-action@v4
        # Only push to Docker Hub if this workflow is a push to mainline
        if: ${{ github.ref == 'refs/heads/master' && github.event_name == 'push' }}
        with:
          tags: jamespfennell/transiter-docs:latest
          file: docs/Dockerfile
          context: .
